"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { Download } from "lucide-react";

export default function FullAuditPage() {
  const [targetUrl, setTargetUrl] = useState("");
  const [auditId, setAuditId] = useState<string | null>(null);
  const [auditState, setAuditState] = useState<any>(null);
  const [errorMessage, setErrorMessage] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  const startAudit = async (e: React.FormEvent) => {
    e.preventDefault();
    const raw = targetUrl.trim();
    if (!raw) {
      setErrorMessage("Please enter a valid website URL.");
      return;
    }

    let urlToScan = raw;
    if (!urlToScan.startsWith("http://") && !urlToScan.startsWith("https://") && !urlToScan.startsWith("benchmark://")) {
      urlToScan = "https://" + urlToScan;
    }

    setIsSubmitting(true);
    setErrorMessage("");
    setAuditState(null);

    try {
      const res = await fetch("/api/audit/full", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: urlToScan }),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.detail || "Audit could not be initiated.");
      
      setAuditId(data.audit_id);
    } catch (err: any) {
      setErrorMessage(err?.message || "Crawler service unreachable.");
      setIsSubmitting(false);
    }
  };

  useEffect(() => {
    if (!auditId) return;

    const interval = setInterval(async () => {
      try {
        const res = await fetch(`/api/audit/full/${auditId}`);
        const data = await res.json();
        setAuditState(data);

        if (data.status === "done" || data.status === "error" || data.status === "DONE" || data.status === "ERROR") {
          clearInterval(interval);
          setIsSubmitting(false);
        }
      } catch (e) {
        console.error(e);
      }
    }, 1500);

    return () => clearInterval(interval);
  }, [auditId]);

  const downloadReport = () => {
    if (!auditState || !auditState.report) return;
    
    // Create a structured textual report that looks somewhat like a PDF download
    const reportData = auditState.report;
    const text = `
DARKSHIELD COMPLIANCE AUDIT REPORT
======================================================
Website: ${reportData.website_url}
Date: ${new Date().toISOString()}

EXECUTIVE SUMMARY
------------------------------------------------------
${reportData.executive_summary}

CRAWL STATISTICS
------------------------------------------------------
Pages Discovered: ${reportData.pages_crawled}
Pages Successfully Analyzed: ${reportData.pages_analyzed}

RISK SUMMARY
------------------------------------------------------
Total Dark Pattern Findings: ${reportData.total_findings}
Critical: ${reportData.severity_breakdown.critical}
High:     ${reportData.severity_breakdown.high}
Medium:   ${reportData.severity_breakdown.medium}
Low:      ${reportData.severity_breakdown.low}

REGULATORY MAPPING
------------------------------------------------------
${reportData.regulatory_mapping.map((m: any) => `- ${m.rule}\n  Notes: ${m.notes}\n  Affected Patterns: ${m.affected_patterns.join(", ")}`).join("\n\n")}

RECOMMENDED REMEDIATION
------------------------------------------------------
${reportData.recommended_remediation.map((r: string) => `- ${r}`).join("\n")}

PAGES REQUIRING IMMEDIATE ATTENTION
------------------------------------------------------
${reportData.pages_requiring_attention.map((p: string) => `- ${p}`).join("\n")}

------------------------------------------------------
Generated by DarkShield (Automated Evidentiary Inspector)
`;

    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `DarkShield_Audit_${new URL(reportData.website_url).hostname}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-[#F7F8FA] text-[#111827] font-sans antialiased">
      {/* Navigation Header */}
      <header className="border-b border-[#E5E7EB] bg-white sticky top-0 z-30">
        <div className="max-w-5xl mx-auto px-6 h-14 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <Link href="/" className="w-7 h-7 rounded bg-[#2563EB] flex items-center justify-center text-white font-bold text-xs cursor-pointer">
              <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5">
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
              </svg>
            </Link>
            <span className="font-semibold text-sm text-[#111827] tracking-tight">DarkShield</span>
            <span className="text-[11px] px-2 py-0.5 rounded bg-[#F9FAFB] border border-[#E5E7EB] text-[#6B7280] font-medium ml-1">
              Full Website Audit
            </span>
          </div>

          <div className="flex items-center gap-5 text-xs text-[#6B7280]">
            <Link href="/" className="hover:text-[#111827] transition-colors font-medium">← Back to Dashboard</Link>
          </div>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 pt-10 pb-16 space-y-8">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-[#111827]">Full Website Compliance Audit</h1>
          <p className="text-sm text-[#6B7280] mt-2">
            Crawls an entire domain (up to maximum limits), extracts evidence across all reachable journeys, and synthesizes a structured regulatory compliance report using Gemini LLM.
          </p>
        </div>

        <div className="bg-white border border-[#E5E7EB] rounded-lg p-6 shadow-xs">
          {!auditId && !isSubmitting ? (
             <form onSubmit={startAudit} className="space-y-4">
               <div>
                 <label className="block text-xs font-semibold text-[#111827] mb-1.5 uppercase tracking-wide">Target Website URL</label>
                 <input
                   type="text"
                   value={targetUrl}
                   onChange={(e) => setTargetUrl(e.target.value)}
                   placeholder="https://example.com"
                   className="w-full px-3 py-2.5 text-sm bg-white border border-gray-300 rounded shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-blue-600 transition-shadow"
                 />
               </div>
               {errorMessage && (
                 <div className="p-3 bg-red-50 border border-red-200 text-red-700 text-xs rounded-md">{errorMessage}</div>
               )}
               <button
                 type="submit"
                 className="w-full sm:w-auto px-6 py-2.5 rounded-md bg-[#111827] hover:bg-[#374151] text-white font-medium text-sm transition-colors cursor-pointer"
               >
                 Start Full Audit
               </button>
             </form>
          ) : (
             <div className="space-y-6">
               
               <div className="flex items-center justify-between border-b border-[#F3F4F6] pb-4">
                 <div>
                   <h3 className="text-sm font-semibold text-[#111827]">Audit Progress</h3>
                   <div className="text-xs text-[#6B7280] mt-1 break-all max-w-lg">
                      {auditState?.current_url ? `Crawling: ${auditState.current_url}` : (auditState?.status === 'done' || auditState?.status === 'DONE' ? 'Audit Complete' : 'Initializing Crawler...')}
                   </div>
                 </div>
                 <div className="flex items-center gap-2">
                    {(auditState?.status === 'done' || auditState?.status === 'DONE') ? (
                       <span className="px-2 py-1 bg-emerald-50 text-emerald-700 text-[11px] font-bold rounded uppercase border border-emerald-200">Complete</span>
                    ) : (
                       <span className="px-2 py-1 bg-blue-50 text-blue-700 text-[11px] font-bold rounded uppercase border border-blue-200 animate-pulse">Running</span>
                    )}
                 </div>
               </div>

               <div className="grid grid-cols-3 gap-4">
                 <div className="p-4 bg-[#F9FAFB] rounded-lg border border-[#E5E7EB]">
                   <div className="text-[11px] font-semibold text-[#6B7280] uppercase tracking-wide">Pages Discovered</div>
                   <div className="text-2xl font-bold text-[#111827] mt-1">{auditState?.pages_discovered || 0}</div>
                 </div>
                 <div className="p-4 bg-[#F9FAFB] rounded-lg border border-[#E5E7EB]">
                   <div className="text-[11px] font-semibold text-[#6B7280] uppercase tracking-wide">Pages Analyzed</div>
                   <div className="text-2xl font-bold text-[#111827] mt-1">{auditState?.pages_analyzed || 0}</div>
                 </div>
                 <div className="p-4 bg-[#F9FAFB] rounded-lg border border-[#E5E7EB]">
                   <div className="text-[11px] font-semibold text-[#6B7280] uppercase tracking-wide">Findings Detected</div>
                   <div className="text-2xl font-bold text-[#111827] mt-1">{auditState?.findings?.length || 0}</div>
                 </div>
               </div>

               {auditState?.status === 'REPORT_READY' && (
                 <div className="text-sm font-medium text-amber-600 animate-pulse">
                   Synthesizing final report with Gemini LLM...
                 </div>
               )}

             </div>
          )}
        </div>

        {/* Audit Report Section (Appears when done) */}
        {(auditState?.status === 'done' || auditState?.status === 'DONE') && auditState?.report && (
           <div className="bg-white border border-[#E5E7EB] rounded-lg shadow-xs overflow-hidden animate-in fade-in slide-in-from-bottom-4 duration-500">
             <div className="bg-[#111827] px-6 py-4 flex items-center justify-between">
               <h2 className="text-white font-semibold text-sm">Regulatory Compliance Report</h2>
               <button 
                  onClick={downloadReport}
                  className="flex items-center gap-2 bg-white/10 hover:bg-white/20 text-white px-3 py-1.5 rounded text-xs font-medium transition-colors"
               >
                  <Download className="w-3.5 h-3.5" />
                  Download Report
               </button>
             </div>
             
             <div className="p-6 space-y-6">
               <div>
                 <h3 className="text-xs font-bold text-[#6B7280] uppercase tracking-wide mb-2">Executive Summary</h3>
                 <p className="text-sm text-[#111827] leading-relaxed">{auditState.report.executive_summary}</p>
               </div>

               <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 pt-4 border-t border-[#F3F4F6]">
                  <div>
                    <div className="text-[11px] font-bold text-red-600 uppercase">Critical Risk</div>
                    <div className="text-xl font-bold text-[#111827]">{auditState.report.severity_breakdown.critical}</div>
                  </div>
                  <div>
                    <div className="text-[11px] font-bold text-amber-600 uppercase">High Risk</div>
                    <div className="text-xl font-bold text-[#111827]">{auditState.report.severity_breakdown.high}</div>
                  </div>
                  <div>
                    <div className="text-[11px] font-bold text-yellow-600 uppercase">Medium Risk</div>
                    <div className="text-xl font-bold text-[#111827]">{auditState.report.severity_breakdown.medium}</div>
                  </div>
                  <div>
                    <div className="text-[11px] font-bold text-emerald-600 uppercase">Low Risk</div>
                    <div className="text-xl font-bold text-[#111827]">{auditState.report.severity_breakdown.low}</div>
                  </div>
               </div>

               <div className="pt-4 border-t border-[#F3F4F6]">
                 <h3 className="text-xs font-bold text-[#6B7280] uppercase tracking-wide mb-3">Regulatory Mapping</h3>
                 <div className="space-y-3">
                   {auditState.report.regulatory_mapping.length > 0 ? auditState.report.regulatory_mapping.map((mapping: any, idx: number) => (
                     <div key={idx} className="bg-[#F9FAFB] p-3 rounded border border-[#E5E7EB]">
                       <div className="text-sm font-semibold text-[#111827]">{mapping.rule}</div>
                       <div className="text-xs text-[#6B7280] mt-1">{mapping.notes}</div>
                       <div className="text-[11px] mt-2 font-mono text-[#4B5563]">Affects: {mapping.affected_patterns.join(', ')}</div>
                     </div>
                   )) : (
                     <div className="text-sm text-[#6B7280]">No mappings triggered.</div>
                   )}
                 </div>
               </div>

               <div className="pt-4 border-t border-[#F3F4F6]">
                 <h3 className="text-xs font-bold text-[#6B7280] uppercase tracking-wide mb-3">Recommended Remediation</h3>
                 <ul className="list-disc pl-5 space-y-1">
                   {auditState.report.recommended_remediation.map((rec: string, idx: number) => (
                      <li key={idx} className="text-sm text-[#111827]">{rec}</li>
                   ))}
                 </ul>
               </div>

               <div className="pt-4 border-t border-[#F3F4F6]">
                 <h3 className="text-xs font-bold text-[#6B7280] uppercase tracking-wide mb-3">Pages Requiring Attention ({auditState.report.pages_requiring_attention.length})</h3>
                 <ul className="space-y-1">
                   {auditState.report.pages_requiring_attention.map((page: string, idx: number) => (
                      <li key={idx} className="text-xs text-[#2563EB] truncate">{page}</li>
                   ))}
                 </ul>
               </div>

             </div>
           </div>
        )}

      </main>
    </div>
  );
}
